---
name: vbf-fs
version: 0.1.0.0
github: "michivi/vbf-fs"
license: MIT
author: "Michivi"
maintainer: "webmaster@michivi.com"
copyright: "2020 Michivi"

extra-source-files:
  - README.md

description: >
  Please see the README on GitHub at
  <https://github.com/michivi/vbf-fs#readme>

dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - containers
  - cryptohash-md5
  - filepath
  - fused-effects
  - vector
  - zlib

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  vbf:
    main: Main.hs
    source-dirs: app/vbf
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-applicative
      - vbf-fs

  vbf-fs:
    main: Main.hs
    source-dirs: app/vbf-fs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HFuse
      - directory
      - optparse-applicative
      - unix
      - vbf-fs
    when:
      - condition: "os(windows)"
        buildable: False
        # No fuse on Windows.

