---
name: vbf-fs
version: 0.1.0.0
github: "michivi/vbf-fs"
license: MIT
author: "Michivi"
maintainer: "webmaster@michivi.com"
copyright: "2020 Michivi"

extra-source-files:
  - README.md

description: >
  This package contains operations and data types for handling VBF archives.
  Those archives are used in various video games to store assets such as
  graphics, sound or videos.

  Please see the README on GitHub at
  <https://github.com/michivi/vbf-fs#readme>

dependencies:
  - base >= 4.7 && < 5
  - binary
  - bytestring
  - containers
  - cryptohash-md5
  - directory
  - filepath
  - vector
  - zlib

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  vbf:
    main: Main.hs
    source-dirs: app/vbf
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - optparse-applicative
      - terminal-progress-bar
      - vbf-fs

  vbf-fs:
    main: Main.hs
    source-dirs: app/vbf-fs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - HFuse
      - optparse-applicative
      - unix
      - vbf-fs
    when:
      - condition: "os(windows)"
        buildable: False
        # No fuse on Windows.

