---
name: vbf-fs
version: 0.1.0.0
github: "michivi/vbf-fs"
license: MIT
author: "Michivi"
maintainer: "webmaster@michivi.com"
copyright: "2020 Michivi"

extra-source-files:
  - README.md

description: >
  Please see the README on GitHub at
  <https://github.com/michivi/vbf-fs#readme>

dependencies:
  - base >= 4.7 && < 5

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  vbf:
    main: Main.hs
    source-dirs: app/vbf
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - vbf-fs
