resolver: lts-16.15

packages:
  - .

extra-deps:
  - git: https://github.com/michivi/hfuse.git
    commit: c305f26b426680d74b8567ddda5cc10b6db56a03
    # nix-sha256: 1myypdcnsmrjdc1mb8cb8gal5s7vya17z798y6rpnlv2nks154x6
  - git: https://github.com/GaloisInc/pure-zlib.git
    commit: 813b6d3160994feee3e0b094e214eed0d5159e92
    # nix-sha256: 0s3dsq6dw4lc3b39qbd9bia87lif9iaqcdc8z3jbhqw2fan7sggx
