---
name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: stack / ghc ${{ matrix.ghc }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        stack:
          - "2.3.3"
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.1"

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get install zlib1g-dev libfuse-dev

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack

      - name: Stack Build
        run: stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks

      - name: Stack Test
        run: stack test --system-ghc
