---
name: CI

on:
  pull_request:
  push:
    branches: [master]

jobs:
  stack:
    name: ${{ matrix.os }} / ghc ${{ matrix.ghc }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macOS-latest
          - ubuntu-latest
          - windows-latest
        stack:
          - "2.3.3"
        ghc:
          - "8.6.5"
          - "8.8.4"
          - "8.10.1"

    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Install dependencies on OSX
        if: matrix.os == 'macOS-latest'
        run: brew cask install osxfuse

      - name: Install dependencies on Linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get install zlib1g-dev libfuse-dev

      - name: Cache Stack dependencies
        uses: actions/cache@v1
        with:
          path: ~/.stack
          key: ${{ runner.os }}-${{ matrix.ghc }}-stack-${{ hashFiles('stack.yaml') }}

      - uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          stack-version: ${{ matrix.stack }}

      - name: Stack Build
        run: stack build --system-ghc --ghc-options=-O2 --test --bench --no-run-tests --no-run-benchmarks

      - name: Stack Test
        run: stack test --system-ghc
